services:
  inngest:
    image: inngest/inngest
    command:
      - inngest
      - dev
      - -u
      - http://host.docker.internal:8000/api/inngest
    ports:
      - "8288:8288"
      - "8289:8289"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
